---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Create the disk mapping file
  include_tasks: create_disk_mapping_file.yml

- name: Mount disks Hana Data
  include_tasks: mount_disk_hana_data.yml

- name: Mount disks Hana Logs
  include_tasks: mount_disk_hana_logs.yml

- name: Mount disks Hana Shared
  include_tasks: mount_disk_hana_shared.yml

- name: Mount disks Hana SAP
  include_tasks: mount_disk_hana_sap.yml

- name: Mount disks Hana Backup
  include_tasks: mount_disk_hana_backup.yml

- name: Mount shared EFS
  include_tasks: mount_disk_sapmnt.yml

- name: Mount disks for Swap
  include_tasks: check_swap_enabled.yml

- name: Reboot instance
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami