---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Ensure dirmngr is installed (gnupg dependency).
  apt:
    name: dirmngr
    state: present

- name: Add ansible repository.
  apt_repository:
    repo: 'ppa:ansible/ansible'
    update_cache: true

- name: Install Ansible.
  apt:
    name: ansible
    state: "{{ ansible_package_state }}"
