---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Install Ansible via Pip.
  pip:
    name: ansible
    version: "{{ ansible_install_version_pip | default(omit) }}"
