---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

all:
  hosts:
    devops-team:
      ansible_host: HOST_NAME_TO_APPLY
      ansible_port: 22
      ansible_user: ec2-user
      ansible_connection: ssh
      ansible_ssh_private_key_file: PATH_TO_PEM_FILE
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=60m"