---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Ensure input parameters were sent as required
  fail: 
    msg: "Variable {{ item }} was not found. Please check again"
  when: lookup('vars', item) is undefined
  loop: "{{ input_variables_to_check|list }}"