---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_http_port: 80

  pre_tasks:
    - include_tasks: java-8.yml

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

  post_tasks:
    - name: Ensure Jenkins is running on the specified port.
      uri:
        url: "http://127.0.0.1:{{ jenkins_http_port }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
