---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_url_prefix: /jenkins

  pre_tasks:
    - include_tasks: java-8.yml

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

  post_tasks:
    - name: Ensure Jenkins is running with the specified prefix.
      uri:
        url: "http://127.0.0.1:80{{ jenkins_url_prefix }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
