---

- name: Ensure Hana database is started
  include_tasks: start_hana.yml

- name: Create database user
  include_tasks: create_db_user.yml

- name: Ensure backup folder {{ backup_folder_path }} exists
  file:
    path: "{{ backup_folder_path }}"
    state: directory
    mode: 0777

- name: Ensure a backup exists for SYSTEM
  shell: |
      source {{ home_path }} && \
      {{ hdbsql_path }} -i {{ GLOBAL_HANA_INSTANCE_NUMBER }} -u SYSTEM -p {{ GLOBAL_MASTER_PASSWORD }} -d SYSTEMDB -m \
      "BACKUP DATA USING FILE ('system_backup')"
  register: sys_bkp_result
  retries: 10
  delay: 5
  until: sys_bkp_result.rc == 0

- name: Ensure a backup exists for {{ GLOBAL_HANA_SID }}
  shell: |
      source {{ home_path }} && \
      {{ hdbsql_path }} -i {{ GLOBAL_HANA_INSTANCE_NUMBER }} -u SYSTEM -p {{ GLOBAL_MASTER_PASSWORD }} -d SYSTEMDB -m \
      "BACKUP DATA FOR {{ GLOBAL_HANA_SID | upper }} USING FILE ('data_bck')"
  register: sid_bkp_result
  retries: 10
  delay: 5
  until: sid_bkp_result.rc == 0
# example: /usr/sap/AD0/HDB00/exe/hdbsql -t -U SYSTEMKEY -j "BACKUP DATA FOR AD0 USING FILE ('/backup/HDB/data')"