---

- name: Wait up to 5 minutes for all configurations to be finished
  command: pcs status
  register: pcs_status
  failed_when: '"Starting" in pcs_status.stdout or "Stopped" in pcs_status.stdout'
  retries: 100
  delay: 3
  until: 'not "Starting" in pcs_status.stdout and not "Stopped" in pcs_status.stdout'

- name: Fail if nodes are not configured
  fail:
    msg: "Configuration for nodes failed. Check the output of pcs status"
  when: 'not "2 nodes configured" in pcs_status.stdout'

- name: Fail if at least one resource/stonith/constraints/orders configurations failed
  fail:
    msg: "Configuration for resources failed. Check the output of pcs status"
  when: '"Failed Resource Actions" in pcs_status.stdout'